version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
    - /home/george/Jenkins/log:/var/log/jenkins
    - /home/george/Jenkins/data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - front_default
  postgres-jenkins:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_DB=agi_test
    ports:
      - 5433:5432
    volumes:
      - /opt/postgres-jenkins:/var/lib/postgresql/data
    networks:
      - front_default
networks:
  front_default:
    driver: bridge